### ISSUE TITLE
Does libmve have a GPL-3 license?

### ISSUE THREAD

**Issue by arbruijn** [btb/d2x#8]
We're looking to use the libmve code originating in d2x in the Descent 3 source port, which has a GPL-3 license. If I understand it correctly, the libmve code is the work of a DXX contributor and so can be used as GPL-3 licensed according to the D2X license. Is that correct?

**Comment by btb** [comment]
I think so. Someone contributed it as a standalone player, but it was adapted by me to use Descent II's original API as closely as possible.

**Comment by arbruijn** [comment]
Thank you. ~Looks like the player code comes from the Baldur's Gate engine [GemBR](https://github.com/gemrb/gemrb/commit/e0ce3575e90b3c98a91b1f9fe38d7675c4c6223e) which is GPL 2+, so we should be fine.~ (edit: this was wrong, the GemBR code actually has a later date)
